name: fuzz
on: [push, pull_request]
jobs:
  fuzz-test:
    name: Fuzz test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Fuzz
        run: ./scripts/run_fuzzer.sh
